server:
  port: 8086
spring:
  main:
    web-application-type: reactive

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  endpoints:
    web:
      exposure:
        include: "*"