package com.ecommerce.common.enums;

public enum ErrorCode {

    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    VALIDATION_FAILED,
    INVALID_REQUEST,
    BUSINESS_RULE_VIOLATION,
    UNAUTHORIZED,
    ACCESS_DENIED,
    INTERNAL_SERVER_ERROR,
    SERVICE_UNAVAILABLE,
    INSUFFICIENT_STOCK,
    PRODUCT_NOT_FOUND,
    PRODUCT_NOT_ACTIVE,
    PAYMENT_ALREADY_EXISTS,
    PAYMENT_NOT_FOUND,
    PAYMENT_FAILED,
    ORDER_NOT_FOUND,
    ORDER_ALREADY_CANCELLED,
    INVALID_ORDER_STATUS,
    INVENTORY_SERVICE_UNAVAILABLE,
}
